# Generated by Django 5.2.11 on 2026-02-19 15:14

import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Company phone with country code",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Company website URL"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Industry or sector", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "companies",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "country"], name="companies_name_2f5024_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "country"), name="unique_company_name_country"
                    )
                ],
            },
        ),
    ]
