# Generated by Django 5.2.11 on 2026-02-20 09:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Phone number with country code (e.g., +1234567890)",
                max_length=128,
                region=None,
                unique=True,
            ),
        ),
    ]
