# Generated by Django 5.2.11 on 2026-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="experience_date",
            field=models.DateField(
                blank=True, help_text="Date of the experience", null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="experience_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Estimated duration in minutes", null=True
            ),
        ),
    ]
