# Generated by Django 5.2.11 on 2026-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_experience_date_review_experience_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="experience_date",
        ),
        migrations.RemoveField(
            model_name="review",
            name="experience_duration",
        ),
        migrations.AddField(
            model_name="review",
            name="faced_company",
            field=models.DateTimeField(
                blank=True,
                help_text="When you faced/interacted with the company",
                null=True,
            ),
        ),
    ]
